### ISSUE TITLE
Peer-to-peer code review 24/05/2022

### ISSUE THREAD

**Issue by lucas-crodrigues** [franclobo/To-Do-List#5]
First of all congratulations on your app, it looks lit 🔥 

The team noticed a bug on your "Clear all completed" button, after reviewing we came up with a solution:
https://github.com/franclobo/To-Do-List/blob/83a5445b3208f3ec55f155a0f4a6d98123d96d4b/src/modules/todolist.js#L56-L60

- [x] You can change this function to call local storage before filtering it, something like:
    `let unlist = JSON.parse(localStorage.getItem('list'));`
    `unlist = unlist.filter((task) => task.completed === false);`
    `localStorage.setItem('list', JSON.stringify(unlist));`
    `window.location.reload();`
    Notice that when using arrow functions the return is implicit if there are no conditions to be met.

- [x] [OPTIONAL] We think it would be more user-friendly if instead of changing the color of the completed tasks, you just change the "check" inside the checkbox.

Cheers! and happy coding 💻

**Comment by franclobo** [comment]
Thank you for helping me with this bug. I've already fixed it.
